config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'shared#index'

  match '/send_support_request' => 'shared#send_support_request', via: [:post]

  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks'}

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, except: [:show, :new, :create] do
    collection do
      match "/dashboard", to: "users#index", via: [:get, :post]
    end
  end

end

app/models/global_config.rb
class GlobalConfig < ActiveRecord::Base
	after_update :update_global_config


	def update_global_config
		self.attributes.each do |attr_name, attr_value|
			APP_CONFIG[attr_name] = attr_value if attr_value != nil && attr_value != ''
		end
	end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider, :user_id
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
  	find_or_create_by(uid: auth.id, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

	# Define what an email should look like
	TEMP_EMAIL_PREFIX = 'change@me'
	TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def is_admin?
    self.admin
  end 

  protected
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def self.provides_callback_for(provider)
		class_eval %Q{
			def #{provider}
				@user = User.find_for_oauth(env["omniauth.auth"], current_user)

				if @user.persisted?
					sign_in_and_redirect @user, event: :authentication
					set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
				else
					sesson["devise.#{provider}_data"] = env["omniauth.auth"]
					redirect_to new_user_registration_url
				end
			end
		}
	end

	[:twitter, :facebook, :linkedin].each do |provider|
		provides_callback_for provider
	end

	def after_sign_in_path_for(resource)
		if resource.email_verified?
			super resource
		else
			finish_signup_path(resource)
		end
	end
end

app/controllers/shared_controller.rb
# This Controller is for all shared pages for the app - landing pages, about, terms of use, etc.

class SharedController < ApplicationController
	layout :resolve_layout #Before rendering check which layout we should show

	def index
		redirect_to dashboard_users_path if current_user
	end

	# From Popup Support Form
	def send_support_request
		require 'slack-poster'

		message = params[:message]
		if current_user
			from = current_user.email
			is_user = 'is a current user'
		else
			from = params[:email]
			is_user = 'is not a current user'
		end

		# Check Type of Request
	  case params[:message_type]
	  when 'technical'
	  	to 			= APP_CONFIG["technical_support_email"]
	  	channel = APP_CONFIG["technical_slack_channel"]
	  when 'feedback'
	  	to 			= APP_CONFIG["feedback_support_email"]
	  	channel = APP_CONFIG["feedback_slack_channel"]
	  else
	  	to 			= APP_CONFIG["default_email_address"]
	  	channel = APP_CONFIG["default_slack_channel"]
	  end

		# Email Appropriate Contact
		AdminMailer.send_support_request(to, from, message, is_user).deliver

		# Send Notification to Slack About Request
		if APP_CONFIG["use_slack"]
			
			options = {
				icon_url: APP_CONFIG["slack_icon_url"],
				username: APP_CONFIG["slack_user"],
				channel: channel
			}
			# Create new poster
			poster = Slack::Poster.new(APP_CONFIG["slack_team"], ENV["SLACK_TOKEN"], options)
			# Prepare message
			slack_message = "#{from} says: #{message} - #{from} #{is_user}"
			# Send slack notification
			poster.send_message(slack_message)
		end

		redirect_to :back, notice: "Message sent to our team!"
	end

	private

		# Determine layout based on action name
	  def resolve_layout
	    case action_name
	    when 'index'
	    	'blank'
	    else
	      'application'
	    end
	  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :resolve_layout #Before rendering check which layout we should show
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]

  # After login go here
  def index

  end

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to root_path, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      if current_user
        @user = current_user
      elsif params[:id]
        @user = User.find(params[:id])
      end
      if @user
        # For Gravatar lookup
        @email_hash = Digest::MD5.hexdigest(@user.email.strip) 
      else
        redirect_to new_user_session_path, alert: 'Please sign in to view dashboard'
      end
    end

    def user_params
      accessible = [:name, :email] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end

    private

    # Determine layout based on action name
    def resolve_layout
      case action_name
      when 'index'
        'dashboard'
      else
        'application'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/layouts/_head.html.erb
<head>
  <title><%= APP_CONFIG["app_name"] %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Rails4Boilerplate</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<% if notice %>
						<p class="notice"><%= notice %></p>
					<% end %>
					<% if alert %>
						<p class="alert"><%= alert %></p>
					<% end %>

					<%= yield %>
				</div>
			</div>
		</div>
		
	</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/head' %>
	<body>

		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<% if notice %>
						<p class="notice"><%= notice %></p>
					<% end %>
					<% if alert %>
						<p class="alert"><%= alert %></p>
					<% end %>
				</div>
			</div>
		</div>

		<%= yield %>

	</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
	<%= render 'layouts/head' %>
  <style type="text/css">body {padding-top: 50px;}</style>
	<body class="dashboard">

   <!-- NAV BAR -->
		<%= render 'layouts/partials/dashboard/nav' %>

    <!-- MAIN CONTENT -->
    <div class="container-fluid">
      <div class="row">

        <!-- SIDEBAR NAV -->
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render 'layouts/partials/dashboard/sidebar' %>
        </div>

        <!-- MAIN CONTENT -->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!-- ALERTS -->
          <div class="container">
            <div class="row">
              <div class="col-xs-12">
                <% if notice %>
                  <p class="notice"><%= notice %></p>
                <% end %>
                <% if alert %>
                  <p class="alert"><%= alert %></p>
                <% end %>
              </div>
            </div>
          </div>

          <!-- PAGES -->
          <%= yield %>

        </div>
      </div>
    </div>

    <!-- Include support form modal -->
    <%= render 'shared/modals/send_support_request' %>

	</body>
</html>

app/views/layouts/partials/dashboard/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= APP_CONFIG["app_name"] %></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Admin Panel', rails_admin_path if current_user.is_admin? %> </li>
        
        <!-- User actions in dropdown -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img src="http://www.gravatar.com/avatar/<%= @email_hash %>?s=23" title="Gravatar" class="gravatar"> <%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">  
            <li><%= link_to "Profile", edit_user_path(id: current_user.id)%></li>
            <li><%= link_to "Account", edit_user_registration_path %> </li>
            <li class="divider"></li>
            <li><a href="#" data-toggle="modal" data-target="#supportModal">Support</a></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>

      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

app/views/layouts/partials/dashboard/_sidebar.html.erb
<ul class="nav nav-sidebar">
  <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
  <li><a href="#">Reports</a></li>
  <li><a href="#">Analytics</a></li>
  <li><a href="#">Export</a></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="">Nav item</a></li>
  <li><a href="">Nav item again</a></li>
  <li><a href="">One more nav</a></li>
  <li><a href="">Another nav item</a></li>
  <li><a href="">More navigation</a></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="">Nav item again</a></li>
  <li><a href="">One more nav</a></li>
  <li><a href="">Another nav item</a></li>
</ul>

app/views/shared/index.html.erb
<style type="text/css">
	html,
	body {
	  height: 100%;
	  background-color: #333;
	}
</style>

<div class="landing-page">
	<div class="site-wrapper">

	  <div class="site-wrapper-inner">

	    <div class="cover-container">

	      <div class="masthead clearfix">
	        <div class="inner">
	          <h3 class="masthead-brand"><%= APP_CONFIG["app_name"] %></h3>
	          <nav>
	            <ul class="nav masthead-nav">
	              <li class="active"><a href="#">Home</a></li>
	              <li><a href="#">Features</a></li>
	              <li><a href="https://twitter.com/TristanToye" target="_blank">Contact</a></li>
	            </ul>
	          </nav>
	        </div>
	      </div>

	      <div class="inner cover">
	        <h1 class="cover-heading">Rails 4 Boilerplate demo.</h1>
	        <p class="lead">The homepage for this demo can be found here: <a href="https://github.com/TristanToye/rails-4-boilerplate" target="_blank" title="GitHub Repo">https://github.com/TristanToye/rails-4-boilerplate</a></p>
	        <p class="lead">
	          <% if !current_user %>
	          	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> <%= link_to "Sign In", new_user_session_path, class: "btn btn-default" %>
						<% else %>
							<h3>Welcome <%= current_user.email %></h3>
							<p><%= link_to "Update Profile", edit_user_path(id: current_user.id), class: "btn btn-default"%> 
								<%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-default"%> 
								<%= link_to 'Admin Panel', rails_admin_path, class: "btn btn-default" if current_user.is_admin? %> 
								<%= link_to 'Logout', destroy_user_session_path, :method => :delete , class: "btn btn-danger" %>
							</p>
						<% end %>
	        </p>
	      </div>

	      <div class="mastfoot">
	        <div class="inner">
	          <p><a href="#" data-toggle="modal" data-target="#supportModal">Support</a></p>
	        </div>
	      </div>

	    </div>

	  </div>

	</div>
</div>

app/views/shared/modals/_send_support_request.html.erb
<!-- Modal -->
<div class="modal fade" id="supportModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">How Can We Help?</h4>
      </div>
      <div class="modal-body">
        <%= form_tag send_support_request_path do %>
        	<div class="form-group">
	        	<label>What type of of request is this?</label>
	        	<select required name="message_type" id="message_type" class="form-control">
	        		<option>Feedback</option>
	        		<option>Technical Support</option>
	        		<option>Other</option>
	        	</select>
        	</div>
        	<% if current_user %>
        		<%= hidden_field_tag :email, current_user.email %>
        	<% else %>
        		<div class="form-group">
	        		<label>Email Address</label>
		        	<%= email_field_tag :email, '', class: "form-control", required: true %>
	        	</div>
        	<% end %>
        	<div class="form-group">
	        	<label>Message</label>
	        	<%= text_area_tag :message, 'What do you want to share with us?', class: "form-control" %>
        	</div>
        	<div class="form-group text-right">
        		<%= submit_tag "Send Support Request", class: "btn btn-primary" %>
        	</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>Edit Profile Info</h2>

<%= form_for(@user, url: user_path(id: @user.id), html: { method: :put }) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="<%= image_path 'ruby-on-rails.jpg' %>" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="<%= image_path 'ruby-on-rails.jpg' %>" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="<%= image_path 'ruby-on-rails.jpg' %>" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="<%= image_path 'ruby-on-rails.jpg' %>" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
</div>

<h2 class="sub-header">Section title</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        <td>cursus</td>
        <td>ante</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>dapibus</td>
        <td>diam</td>
        <td>Sed</td>
        <td>nisi</td>
      </tr>
      <tr>
        <td>1,005</td>
        <td>Nulla</td>
        <td>quis</td>
        <td>sem</td>
        <td>at</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>nibh</td>
        <td>elementum</td>
        <td>imperdiet</td>
        <td>Duis</td>
      </tr>
      <tr>
        <td>1,007</td>
        <td>sagittis</td>
        <td>ipsum</td>
        <td>Praesent</td>
        <td>mauris</td>
      </tr>
      <tr>
        <td>1,008</td>
        <td>Fusce</td>
        <td>nec</td>
        <td>tellus</td>
        <td>sed</td>
      </tr>
      <tr>
        <td>1,009</td>
        <td>augue</td>
        <td>semper</td>
        <td>porta</td>
        <td>Mauris</td>
      </tr>
      <tr>
        <td>1,010</td>
        <td>massa</td>
        <td>Vestibulum</td>
        <td>lacinia</td>
        <td>arcu</td>
      </tr>
      <tr>
        <td>1,011</td>
        <td>eget</td>
        <td>nulla</td>
        <td>Class</td>
        <td>aptent</td>
      </tr>
      <tr>
        <td>1,012</td>
        <td>taciti</td>
        <td>sociosqu</td>
        <td>ad</td>
        <td>litora</td>
      </tr>
      <tr>
        <td>1,013</td>
        <td>torquent</td>
        <td>per</td>
        <td>conubia</td>
        <td>nostra</td>
      </tr>
      <tr>
        <td>1,014</td>
        <td>per</td>
        <td>inceptos</td>
        <td>himenaeos</td>
        <td>Curabitur</td>
      </tr>
      <tr>
        <td>1,015</td>
        <td>sodales</td>
        <td>ligula</td>
        <td>in</td>
        <td>libero</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>